FROM {{runtimeBuilderImage}} AS runtime
FROM {{fullBaseImage}}

{{baseSetupStep}}

RUN mkdir -p /opt/remote-target/runtime
COPY --from=runtime {{runtimeBinarySourcePath}} {{runtimeBinaryPath}}

{{runtimeSetupStep}}

RUN set -eux; \
	mkdir -p /root/.ssh; \
	chmod 700 /root/.ssh; \
	printf '%s' '{{sshPublicKeyBase64}}' | base64 -d > /root/.ssh/authorized_keys; \
	chmod 600 /root/.ssh/authorized_keys

{{sshServerSetupStep}}

EXPOSE 22
CMD {{sshServerCommand}}
